### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by apiraino** [Stratio/vagrant-ova-plugin#1]
Hi,

when I try to install the plugin, i receive this Ruby error:

```
$ vagrant plugin install vagrant-ova-plugin-0.1.0.gem
Installing the 'vagrant-ova-plugin-0.1.0.gem' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/package.rb:522:in `rescue in verify': No such file or directory @ rb_sysopen - vagrant-ova-plugin-0.1.0.gem (Gem::Package::FormatError)
    from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/package.rb:500:in `verify'
    from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/package.rb:484:in `spec'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:134:in `block in install_local'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:294:in `block in with_isolated_gem'
    from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/user_interaction.rb:45:in `use_ui'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:293:in `with_isolated_gem'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:131:in `install_local'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/plugin/manager.rb:47:in `install_plugin'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/action/install_gem.rb:37:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/base.rb:14:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/install.rb:32:in `block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/install.rb:31:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/install.rb:31:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/root.rb:56:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:308:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:174:in `<main>'
```

Currently using `Vagrant 1.8.6`.

Tried using Ruby (installed with rvm) `ruby-1.9.3-p551 [ x86_64 ]` and `ruby-2.2.1 [ x86_64 ]`

Any clues?

thanks,
A.

**Comment by marcosdotps** [comment]
Hi @apiraino!

I've also faced this problem, and it's not related to the plugin. This might be caused by some issue on debian vagrant package.

Could you try purging the Debian vagrant package and installing from [https://www.vagrantup.com/downloads.html](https://www.vagrantup.com/downloads.html)?

Let me know if it works for you!

Thanks,

Marcos

**Comment by apiraino** [comment]
Hi,

thanks for the reply. I'm already using the vanilla package from vagrantup.com. I've updated to Vagrant 1.9.2 and after some tricks (involving a plugin repair), the installation was successful.

However I still cannot use the plugin:
```
$ vagrant ova --output /tmp/example.ova
Including Minitar via the Archive::Tar namespace is deprecated.
/home/jman/.vagrant.d/gems/2.2.5/gems/vagrant-ova-0.1.0/lib/vagrant-ova/plugin.rb:34:in `execute': undefined method `name' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.2/bin/vagrant:127:in `<main>'
```
